[package]
name = "storage-hub-primitives"
description = "Support primitives used in StorageHub"
version = "0.1.0"
homepage = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bincode = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }

# Local
storage-hub-traits = { workspace = true }

# Substrate
sp-core = { workspace = true }
sp-trie = { workspace = true }

reference-trie = { workspace = true }
trie-db = { workspace = true }

frame-support = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
frame-system = { workspace = true, features = ["std"]}

# Substrate
sp-io = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = [
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "storage-hub-traits/runtime-benchmarks",
]
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "scale-info/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-trie/std",
    "storage-hub-traits/std",
]
try-runtime = [
    "frame-support/try-runtime",
    "frame-system/try-runtime",
    "sp-runtime/try-runtime",
    "storage-hub-traits/try-runtime",
]
