
//! Autogenerated weights for `pallet_storage_providers`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2024-11-15, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Tobi-G14`, CPU: `AMD Ryzen 9 7940HS w/ Radeon 780M Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/production/wbuild/storage-hub-runtime/storage_hub_runtime.wasm
// --pallet
// pallet_storage_providers
// --extrinsic
// 
// --output
// pallets/providers/src/weights.rs
// --template
// ../../personal/polkadot/polkadot-sdk/substrate/.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_storage_providers`.
pub trait WeightInfo {
	fn request_msp_sign_up() -> Weight;
	fn request_bsp_sign_up() -> Weight;
	fn confirm_sign_up_bsp() -> Weight;
	fn confirm_sign_up_msp() -> Weight;
	fn cancel_sign_up() -> Weight;
	fn msp_sign_off() -> Weight;
	fn bsp_sign_off() -> Weight;
	fn change_capacity_bsp_less_deposit() -> Weight;
	fn change_capacity_bsp_more_deposit() -> Weight;
	fn change_capacity_msp_less_deposit() -> Weight;
	fn change_capacity_msp_more_deposit() -> Weight;
	fn add_value_prop() -> Weight;
	fn make_value_prop_unavailable() -> Weight;
	fn add_multiaddress() -> Weight;
	fn remove_multiaddress() -> Weight;
	fn force_msp_sign_up() -> Weight;
	fn force_bsp_sign_up() -> Weight;
	fn slash() -> Weight;
}

/// Weights for `pallet_storage_providers` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Providers::SignUpRequests` (r:1 w:1)
	/// Proof: `Providers::SignUpRequests` (`max_values`: None, `max_size`: Some(1679), added: 4154, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	fn request_msp_sign_up() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `5144`
		// Minimum execution time: 61_059_000 picoseconds.
		Weight::from_parts(62_537_000, 5144)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Providers::SignUpRequests` (r:1 w:1)
	/// Proof: `Providers::SignUpRequests` (`max_values`: None, `max_size`: Some(1679), added: 4154, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	fn request_bsp_sign_up() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `5144`
		// Minimum execution time: 66_729_000 picoseconds.
		Weight::from_parts(67_999_000, 5144)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Providers::SignUpRequests` (r:1 w:1)
	/// Proof: `Providers::SignUpRequests` (`max_values`: None, `max_size`: Some(1679), added: 4154, mode: `MaxEncodedLen`)
	/// Storage: `Randomness::LatestOneEpochAgoRandomness` (r:1 w:0)
	/// Proof: `Randomness::LatestOneEpochAgoRandomness` (`max_values`: Some(1), `max_size`: Some(36), added: 531, mode: `MaxEncodedLen`)
	/// Storage: `Providers::TotalBspsCapacity` (r:1 w:1)
	/// Proof: `Providers::TotalBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BspCount` (r:1 w:1)
	/// Proof: `Providers::BspCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::GlobalBspsReputationWeight` (r:1 w:1)
	/// Proof: `Providers::GlobalBspsReputationWeight` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:0 w:1)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:0 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	fn confirm_sign_up_bsp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `411`
		//  Estimated: `5144`
		// Minimum execution time: 27_060_000 picoseconds.
		Weight::from_parts(28_984_000, 5144)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Providers::SignUpRequests` (r:1 w:1)
	/// Proof: `Providers::SignUpRequests` (`max_values`: None, `max_size`: Some(1679), added: 4154, mode: `MaxEncodedLen`)
	/// Storage: `Randomness::LatestOneEpochAgoRandomness` (r:1 w:0)
	/// Proof: `Randomness::LatestOneEpochAgoRandomness` (`max_values`: Some(1), `max_size`: Some(36), added: 531, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MspCount` (r:1 w:1)
	/// Proof: `Providers::MspCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:0 w:1)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:0 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(647), added: 3122, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::PrivilegedProviders` (r:0 w:1)
	/// Proof: `PaymentStreams::PrivilegedProviders` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn confirm_sign_up_msp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `404`
		//  Estimated: `5144`
		// Minimum execution time: 35_154_000 picoseconds.
		Weight::from_parts(38_046_000, 5144)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Providers::SignUpRequests` (r:1 w:1)
	/// Proof: `Providers::SignUpRequests` (`max_values`: None, `max_size`: Some(1679), added: 4154, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn cancel_sign_up() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `502`
		//  Estimated: `5144`
		// Minimum execution time: 45_111_000 picoseconds.
		Weight::from_parts(46_671_000, 5144)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:1)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(647), added: 3122, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MspCount` (r:1 w:1)
	/// Proof: `Providers::MspCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::PrivilegedProviders` (r:0 w:1)
	/// Proof: `PaymentStreams::PrivilegedProviders` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn msp_sign_off() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `623`
		//  Estimated: `4112`
		// Minimum execution time: 53_953_000 picoseconds.
		Weight::from_parts(55_795_000, 4112)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:1)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `Providers::TotalBspsCapacity` (r:1 w:1)
	/// Proof: `Providers::TotalBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BspCount` (r:1 w:1)
	/// Proof: `Providers::BspCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::GlobalBspsReputationWeight` (r:1 w:1)
	/// Proof: `Providers::GlobalBspsReputationWeight` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn bsp_sign_off() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `673`
		//  Estimated: `4148`
		// Minimum execution time: 57_803_000 picoseconds.
		Weight::from_parts(61_995_000, 4148)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Providers::TotalBspsCapacity` (r:1 w:1)
	/// Proof: `Providers::TotalBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn change_capacity_bsp_less_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `673`
		//  Estimated: `4148`
		// Minimum execution time: 56_804_000 picoseconds.
		Weight::from_parts(59_551_000, 4148)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Providers::TotalBspsCapacity` (r:1 w:1)
	/// Proof: `Providers::TotalBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn change_capacity_bsp_more_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `673`
		//  Estimated: `4148`
		// Minimum execution time: 71_410_000 picoseconds.
		Weight::from_parts(74_459_000, 4148)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(647), added: 3122, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn change_capacity_msp_less_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `623`
		//  Estimated: `4112`
		// Minimum execution time: 52_830_000 picoseconds.
		Weight::from_parts(55_119_000, 4112)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(647), added: 3122, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn change_capacity_msp_more_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `623`
		//  Estimated: `4112`
		// Minimum execution time: 68_248_000 picoseconds.
		Weight::from_parts(69_881_000, 4112)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	fn add_value_prop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `355`
		//  Estimated: `4588`
		// Minimum execution time: 24_604_000 picoseconds.
		Weight::from_parts(25_884_000, 4588)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	fn make_value_prop_unavailable() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `395`
		//  Estimated: `4588`
		// Minimum execution time: 19_142_000 picoseconds.
		Weight::from_parts(21_327_000, 4588)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	fn add_multiaddress() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `444`
		//  Estimated: `4148`
		// Minimum execution time: 22_899_000 picoseconds.
		Weight::from_parts(31_991_000, 4148)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	fn remove_multiaddress() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `852`
		//  Estimated: `4148`
		// Minimum execution time: 24_917_000 picoseconds.
		Weight::from_parts(26_685_000, 4148)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Providers::SignUpRequests` (r:1 w:1)
	/// Proof: `Providers::SignUpRequests` (`max_values`: None, `max_size`: Some(1679), added: 4154, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:1)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MspCount` (r:1 w:1)
	/// Proof: `Providers::MspCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:0 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(647), added: 3122, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::PrivilegedProviders` (r:0 w:1)
	/// Proof: `PaymentStreams::PrivilegedProviders` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn force_msp_sign_up() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `5144`
		// Minimum execution time: 83_771_000 picoseconds.
		Weight::from_parts(85_883_000, 5144)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: `Providers::SignUpRequests` (r:1 w:1)
	/// Proof: `Providers::SignUpRequests` (`max_values`: None, `max_size`: Some(1679), added: 4154, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:1)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `Providers::TotalBspsCapacity` (r:1 w:1)
	/// Proof: `Providers::TotalBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BspCount` (r:1 w:1)
	/// Proof: `Providers::BspCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::GlobalBspsReputationWeight` (r:1 w:1)
	/// Proof: `Providers::GlobalBspsReputationWeight` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:0 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	fn force_bsp_sign_up() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `5144`
		// Minimum execution time: 75_083_000 picoseconds.
		Weight::from_parts(76_457_000, 5144)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: `Providers::MainStorageProviders` (r:1 w:0)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(647), added: 3122, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:0)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `ProofsDealer::SlashableProviders` (r:1 w:1)
	/// Proof: `ProofsDealer::SlashableProviders` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:1 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn slash() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `867`
		//  Estimated: `6196`
		// Minimum execution time: 62_963_000 picoseconds.
		Weight::from_parts(65_689_000, 6196)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Providers::SignUpRequests` (r:1 w:1)
	/// Proof: `Providers::SignUpRequests` (`max_values`: None, `max_size`: Some(1679), added: 4154, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	fn request_msp_sign_up() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `5144`
		// Minimum execution time: 61_059_000 picoseconds.
		Weight::from_parts(62_537_000, 5144)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Providers::SignUpRequests` (r:1 w:1)
	/// Proof: `Providers::SignUpRequests` (`max_values`: None, `max_size`: Some(1679), added: 4154, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	fn request_bsp_sign_up() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `5144`
		// Minimum execution time: 66_729_000 picoseconds.
		Weight::from_parts(67_999_000, 5144)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Providers::SignUpRequests` (r:1 w:1)
	/// Proof: `Providers::SignUpRequests` (`max_values`: None, `max_size`: Some(1679), added: 4154, mode: `MaxEncodedLen`)
	/// Storage: `Randomness::LatestOneEpochAgoRandomness` (r:1 w:0)
	/// Proof: `Randomness::LatestOneEpochAgoRandomness` (`max_values`: Some(1), `max_size`: Some(36), added: 531, mode: `MaxEncodedLen`)
	/// Storage: `Providers::TotalBspsCapacity` (r:1 w:1)
	/// Proof: `Providers::TotalBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BspCount` (r:1 w:1)
	/// Proof: `Providers::BspCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::GlobalBspsReputationWeight` (r:1 w:1)
	/// Proof: `Providers::GlobalBspsReputationWeight` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:0 w:1)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:0 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	fn confirm_sign_up_bsp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `411`
		//  Estimated: `5144`
		// Minimum execution time: 27_060_000 picoseconds.
		Weight::from_parts(28_984_000, 5144)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `Providers::SignUpRequests` (r:1 w:1)
	/// Proof: `Providers::SignUpRequests` (`max_values`: None, `max_size`: Some(1679), added: 4154, mode: `MaxEncodedLen`)
	/// Storage: `Randomness::LatestOneEpochAgoRandomness` (r:1 w:0)
	/// Proof: `Randomness::LatestOneEpochAgoRandomness` (`max_values`: Some(1), `max_size`: Some(36), added: 531, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MspCount` (r:1 w:1)
	/// Proof: `Providers::MspCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:0 w:1)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:0 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(647), added: 3122, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::PrivilegedProviders` (r:0 w:1)
	/// Proof: `PaymentStreams::PrivilegedProviders` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn confirm_sign_up_msp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `404`
		//  Estimated: `5144`
		// Minimum execution time: 35_154_000 picoseconds.
		Weight::from_parts(38_046_000, 5144)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `Providers::SignUpRequests` (r:1 w:1)
	/// Proof: `Providers::SignUpRequests` (`max_values`: None, `max_size`: Some(1679), added: 4154, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn cancel_sign_up() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `502`
		//  Estimated: `5144`
		// Minimum execution time: 45_111_000 picoseconds.
		Weight::from_parts(46_671_000, 5144)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:1)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(647), added: 3122, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MspCount` (r:1 w:1)
	/// Proof: `Providers::MspCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::PrivilegedProviders` (r:0 w:1)
	/// Proof: `PaymentStreams::PrivilegedProviders` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn msp_sign_off() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `623`
		//  Estimated: `4112`
		// Minimum execution time: 53_953_000 picoseconds.
		Weight::from_parts(55_795_000, 4112)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:1)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `Providers::TotalBspsCapacity` (r:1 w:1)
	/// Proof: `Providers::TotalBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BspCount` (r:1 w:1)
	/// Proof: `Providers::BspCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::GlobalBspsReputationWeight` (r:1 w:1)
	/// Proof: `Providers::GlobalBspsReputationWeight` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn bsp_sign_off() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `673`
		//  Estimated: `4148`
		// Minimum execution time: 57_803_000 picoseconds.
		Weight::from_parts(61_995_000, 4148)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Providers::TotalBspsCapacity` (r:1 w:1)
	/// Proof: `Providers::TotalBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn change_capacity_bsp_less_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `673`
		//  Estimated: `4148`
		// Minimum execution time: 56_804_000 picoseconds.
		Weight::from_parts(59_551_000, 4148)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Providers::TotalBspsCapacity` (r:1 w:1)
	/// Proof: `Providers::TotalBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn change_capacity_bsp_more_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `673`
		//  Estimated: `4148`
		// Minimum execution time: 71_410_000 picoseconds.
		Weight::from_parts(74_459_000, 4148)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(647), added: 3122, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn change_capacity_msp_less_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `623`
		//  Estimated: `4112`
		// Minimum execution time: 52_830_000 picoseconds.
		Weight::from_parts(55_119_000, 4112)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(647), added: 3122, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn change_capacity_msp_more_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `623`
		//  Estimated: `4112`
		// Minimum execution time: 68_248_000 picoseconds.
		Weight::from_parts(69_881_000, 4112)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	fn add_value_prop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `355`
		//  Estimated: `4588`
		// Minimum execution time: 24_604_000 picoseconds.
		Weight::from_parts(25_884_000, 4588)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	fn make_value_prop_unavailable() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `395`
		//  Estimated: `4588`
		// Minimum execution time: 19_142_000 picoseconds.
		Weight::from_parts(21_327_000, 4588)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	fn add_multiaddress() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `444`
		//  Estimated: `4148`
		// Minimum execution time: 22_899_000 picoseconds.
		Weight::from_parts(31_991_000, 4148)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	fn remove_multiaddress() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `852`
		//  Estimated: `4148`
		// Minimum execution time: 24_917_000 picoseconds.
		Weight::from_parts(26_685_000, 4148)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Providers::SignUpRequests` (r:1 w:1)
	/// Proof: `Providers::SignUpRequests` (`max_values`: None, `max_size`: Some(1679), added: 4154, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:1)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MspCount` (r:1 w:1)
	/// Proof: `Providers::MspCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:0 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(647), added: 3122, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::PrivilegedProviders` (r:0 w:1)
	/// Proof: `PaymentStreams::PrivilegedProviders` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn force_msp_sign_up() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `5144`
		// Minimum execution time: 83_771_000 picoseconds.
		Weight::from_parts(85_883_000, 5144)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: `Providers::SignUpRequests` (r:1 w:1)
	/// Proof: `Providers::SignUpRequests` (`max_values`: None, `max_size`: Some(1679), added: 4154, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:1)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `Providers::TotalBspsCapacity` (r:1 w:1)
	/// Proof: `Providers::TotalBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BspCount` (r:1 w:1)
	/// Proof: `Providers::BspCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::GlobalBspsReputationWeight` (r:1 w:1)
	/// Proof: `Providers::GlobalBspsReputationWeight` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:0 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	fn force_bsp_sign_up() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `5144`
		// Minimum execution time: 75_083_000 picoseconds.
		Weight::from_parts(76_457_000, 5144)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: `Providers::MainStorageProviders` (r:1 w:0)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(647), added: 3122, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:0)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `ProofsDealer::SlashableProviders` (r:1 w:1)
	/// Proof: `ProofsDealer::SlashableProviders` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:1 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn slash() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `867`
		//  Estimated: `6196`
		// Minimum execution time: 62_963_000 picoseconds.
		Weight::from_parts(65_689_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
}
