# StorageHub Backend Configuration

# Server settings
host = "127.0.0.1"
port = 8080

# StorageHub node connection
[storage_hub]
rpc_url = "ws://localhost:9944"
# mock_mode = true  # Uncomment when using "mocks" feature

# Database connection
# NOTE: PostgreSQL must be running for the backend to start
# Example connection strings:
# - Local: "postgres://postgres:password@localhost:5432/storage_hub"
# - Docker: "postgres://postgres:password@postgres:5432/storage_hub"
[database]
url = "postgres://postgres:password@localhost:5432/storage_hub"
# mock_mode = true  # Uncomment when using "mocks" feature