# StorageHub Backend Test Configuration
# This configuration is for testing without a real PostgreSQL database

# Server settings
host = "127.0.0.1"
port = 8080

# StorageHub node connection
[storage_hub]
rpc_url = "ws://localhost:9944"

# Database connection - using invalid URL to test fallback behavior
[database]
url = "postgres://localhost:5432/storage_hub_test"