[provider]
# BSP provider type
provider_type = "bsp"
# Using memory storage layer for simplicity
storage_layer = "memory"
# Maximum storage capacity in bytes (4GB)
max_storage_capacity = 4294967295
# Jump capacity in bytes (1GB)
jump_capacity = 1073741824
# Extrinsic retry timeout in seconds
extrinsic_retry_timeout = 60
# The minimum number of blocks behind the current best block to consider the node out of sync.
sync_mode_min_blocks_behind = 5
# On blocks that are multiples of this number, the blockchain service will trigger the catch of proofs.
check_for_pending_proofs_period = 4
# The maximum number of blocks from the past that will be processed for catching up the root changes.
max_blocks_behind_to_catch_up_root_changes = 10
# Node key for identity
node_key = "0x2e6e3670c96202a2d6f5a58b7ac9092c5a51e0250f324eec2111ca94f5e568be"
# Path to keystores
keystore_path = "./docker/dev-keystores"
# Configuration for the BSP Upload File task
[provider.bsp_upload_file]
# Maximum number of times to retry file upload operations
max_try_count = 5
# Maximum tip amount to use when submitting file upload extrinsics
max_tip = 100.0

# Configuration for the BSP Move Bucket task
[provider.bsp_move_bucket]
# Grace period in seconds to accept download requests after a bucket move is accepted
move_bucket_accepted_grace_period = 14400

# Configuration for the BSP Charge Fees task
[provider.bsp_charge_fees]
# Minimum debt threshold for charging users
min_debt = 0

# Configuration for the BSP Submit Proof task
[provider.bsp_submit_proof]
# Maximum number of attempts to submit a proof
max_submission_attempts = 5

# Configuration for the Blockchain Service
[provider.blockchain_service]
extrinsic_retry_timeout = 60

# Optional indexer configuration
[indexer]
# Set to true to enable the indexer
indexer = true
database_url = "postgresql://postgres:postgres@docker-sh-postgres-1:5432/storage_hub"
