[provider]
# MSP provider type
provider_type = "msp"
# Using memory storage layer for simplicity
storage_layer = "memory"
# Maximum storage capacity in bytes (4GB)
max_storage_capacity = 4294967295
# Jump capacity in bytes (1GB)
jump_capacity = 1073741824
# Extrinsic retry timeout in seconds
extrinsic_retry_timeout = 60
# Node key for identity
node_key = "0x2e6e3670c96202a2d6f5a58b7ac9092c5a51e0250f324eec2111ca94f5e568be"
# Path to keystores
keystore_path = "./docker/dev-keystores"

# Configuration for the MSP Delete File task
[provider.msp_delete_file]
# Maximum number of times to retry a file deletion request
max_try_count = 5
# Maximum tip amount to use when submitting a file deletion request extrinsic
max_tip = 100.0

# Configuration for the MSP Charge Fees task
[provider.msp_charge_fees]
# Minimum debt threshold for charging users
min_debt = 0

# Configuration for the MSP Move Bucket task
[provider.msp_move_bucket]
# Maximum number of times to retry move bucket operations
max_try_count = 5
# Maximum tip amount to use when submitting move bucket extrinsics
max_tip = 100.0
# Interval in seconds for processing move bucket requests
processing_interval = 60
# Maximum number of files to download in parallel
max_concurrent_file_downloads = 5
# Maximum number of chunks requests to do in parallel per file
max_concurrent_chunks_per_file = 5
# Maximum number of chunks to request in a single network request
max_chunks_per_request = 10
# Number of peers to select for each chunk download attempt (2 best + x random)
chunk_request_peer_retry_attempts = 2
# Number of retries per peer for a single chunk request
download_retry_attempts = 3

# Configuration for the Blockchain Service
[provider.blockchain_service]
# Currently no settings needed, reserved for future use

# Configuration for the File Transfer Service
[provider.file_transfer_service]
# Currently no settings needed, reserved for future use

# Optional indexer configuration
[indexer]
# Set to true to enable the indexer
indexer = true
database_url = "postgresql://postgres:postgres@docker-sh-postgres-1:5432/storage_hub"
