[provider]
# MSP provider type
provider_type = "msp"
# Using memory storage layer for simplicity
storage_layer = "memory"
# Maximum storage capacity in bytes (4GB)
max_storage_capacity = 4294967295
# Jump capacity in bytes (1GB)
jump_capacity = 1073741824
# Extrinsic retry timeout in seconds
extrinsic_retry_timeout = 60
# The minimum number of blocks behind the current best block to consider the node out of sync.
sync_mode_min_blocks_behind = 5
# On blocks that are multiples of this number, the blockchain service will trigger the catch of proofs.
check_for_pending_proofs_period = 4
# The maximum number of blocks from the past that will be processed for catching up the root changes.
max_blocks_behind_to_catch_up_root_changes = 10
# Node key for identity
node_key = "0x2e6e3670c96202a2d6f5a58b7ac9092c5a51e0250f324eec2111ca94f5e568be"
# Path to keystores
keystore_path = "./docker/dev-keystores"

# Configuration for the MSP Charge Fees task
[provider.msp_charge_fees]
# Minimum debt threshold for charging users
min_debt = 0

# Configuration for the MSP Move Bucket task
[provider.msp_move_bucket]
# Maximum number of times to retry move bucket operations
max_try_count = 5
# Maximum tip amount to use when submitting move bucket extrinsics
max_tip = 100.0

# Configuration for the Blockchain Service
[provider.blockchain_service]
extrinsic_retry_timeout = 60

# RPC configuration
[provider.rpc_config]
# Remote file configuration
[provider.rpc_config.remote_file]
# Maximum file size in bytes (default: 10GB)
max_file_size = 10737418240
# Connection timeout in seconds (default: 30)
connection_timeout = 30
# Read timeout in seconds (default: 300)
read_timeout = 300
# Whether to follow redirects (default: true)
follow_redirects = true
# Maximum number of redirects (default: 10)
max_redirects = 10
# User agent string (default: "StorageHub-Client/1.0")
user_agent = "StorageHub-Client/1.0"
# Chunk size in bytes. This is different from the FILE_CHUNK_SIZE constant in the runtime, as it only affects file upload/download. (default: 8KB)
chunk_size = 8192
# Number of `chunk_size` chunks to buffer during upload/download. (default: 512)
chunks_buffer = 512

# Optional indexer configuration
[indexer]
database_url = "postgresql://postgres:postgres@storage-hub-sh-postgres-1:5432/storage_hub"
