packages:
  - api-augment
  - scripts
  - types-bundle
  - test
  - sdk
  - sdk/core
  - sdk/msp-client

onlyBuiltDependencies:
  - '@biomejs/biome'
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2
