// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_file_system`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 52.0.0
//! DATE: 2026-02-17, STEPS: `3`, REPEAT: `3`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Mac`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/sh-parachain-runtime/sh_parachain_runtime.wasm
// --pallet
// pallet-file-system
// --extrinsic
// *
// --exclude-extrinsics
// pallet_file_system::bsp_confirm_stop_storing,pallet_file_system::create_and_associate_collection_with_bucket,pallet_file_system::create_bucket,pallet_file_system::delete_bucket,pallet_file_system::issue_storage_request,pallet_file_system::msp_respond_move_bucket_request,pallet_file_system::msp_stop_storing_bucket,pallet_file_system::msp_stop_storing_bucket_for_insolvent_user,pallet_file_system::on_poll_hook,pallet_file_system::process_expired_move_bucket_request,pallet_file_system::request_move_bucket,pallet_file_system::stop_storing_for_insolvent_user_bsp,pallet_file_system::stop_storing_for_insolvent_user_msp,pallet_file_system::update_bucket_privacy,pallet_file_system::bsp_confirm_storing,pallet_file_system::bsp_request_stop_storing
// --output
// pallets/file-system/src/weights_branch.rs
// --template
// .maintain/frame-weight-template.hbs
// --steps
// 3
// --repeat
// 3

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_file_system`.
pub trait WeightInfo {
	fn revoke_storage_request(n: u32, ) -> Weight;
	fn msp_respond_storage_requests_multiple_buckets(n: u32, m: u32, l: u32, ) -> Weight;
	fn bsp_volunteer() -> Weight;
	fn process_expired_storage_request_msp_accepted_or_no_msp(n: u32, ) -> Weight;
	fn process_expired_storage_request_msp_rejected(n: u32, ) -> Weight;
	fn delete_files_bucket(n: u32, ) -> Weight;
	fn delete_files_bsp(n: u32, ) -> Weight;
	fn delete_files_for_incomplete_storage_request_bucket(n: u32, ) -> Weight;
	fn delete_files_for_incomplete_storage_request_bsp(n: u32, ) -> Weight;
}

/// Weights for `pallet_file_system` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1916), added: 4391, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 39]`.
	fn revoke_storage_request(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1724 + n * (33 ±0)`
		//  Estimated: `6687`
		// Minimum execution time: 66_000_000 picoseconds.
		Weight::from_parts(67_707_602, 6687)
			// Standard Error: 61_164
			.saturating_add(Weight::from_parts(570_175, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(667), added: 3142, mode: `MaxEncodedLen`)
	/// Storage: `Providers::Buckets` (r:10 w:10)
	/// Proof: `Providers::Buckets` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Providers::InsolventProviders` (r:2 w:0)
	/// Proof: `Providers::InsolventProviders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AwaitingTopUpFromProviders` (r:2 w:0)
	/// Proof: `Providers::AwaitingTopUpFromProviders` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:200 w:200)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:3 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:0)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::FixedRatePaymentStreams` (r:1 w:0)
	/// Proof: `PaymentStreams::FixedRatePaymentStreams` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:0)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:200)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	/// The range of component `m` is `[1, 10]`.
	/// The range of component `l` is `[1, 10]`.
	fn msp_respond_storage_requests_multiple_buckets(n: u32, m: u32, l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + l * (7457 ±0) + m * (15308 ±0) + n * (22985 ±0)`
		//  Estimated: `101170 + l * (5992 ±7_525) + m * (5992 ±7_525) + n * (56082 ±0)`
		// Minimum execution time: 1_831_000_000 picoseconds.
		Weight::from_parts(1_831_000_000, 101170)
			// Standard Error: 138_080_117
			.saturating_add(Weight::from_parts(1_049_582_991, 0).saturating_mul(n.into()))
			// Standard Error: 138_080_117
			.saturating_add(Weight::from_parts(673_202_488, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(38_u64))
			.saturating_add(T::DbWeight::get().reads((12_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(l.into())))
			.saturating_add(T::DbWeight::get().writes(45_u64))
			.saturating_add(T::DbWeight::get().writes((23_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(l.into())))
			.saturating_add(Weight::from_parts(0, 5992).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 5992).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 56082).saturating_mul(n.into()))
	}
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::InsolventProviders` (r:2 w:0)
	/// Proof: `Providers::InsolventProviders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AwaitingTopUpFromProviders` (r:2 w:0)
	/// Proof: `Providers::AwaitingTopUpFromProviders` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:0)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:3 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ProofsDealer::ChallengesTicker` (r:1 w:0)
	/// Proof: `ProofsDealer::ChallengesTicker` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::GlobalBspsReputationWeight` (r:1 w:0)
	/// Proof: `Providers::GlobalBspsReputationWeight` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bsp_volunteer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2547`
		//  Estimated: `8523`
		// Minimum execution time: 99_000_000 picoseconds.
		Weight::from_parts(100_000_000, 8523)
			.saturating_add(T::DbWeight::get().reads(16_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 39]`.
	fn process_expired_storage_request_msp_accepted_or_no_msp(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1724 + n * (33 ±0)`
		//  Estimated: `6687`
		// Minimum execution time: 49_000_000 picoseconds.
		Weight::from_parts(50_436_459, 6687)
			// Standard Error: 177_937
			.saturating_add(Weight::from_parts(419_953, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1916), added: 4391, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 39]`.
	fn process_expired_storage_request_msp_rejected(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1724 + n * (33 ±0)`
		//  Estimated: `6687`
		// Minimum execution time: 53_000_000 picoseconds.
		Weight::from_parts(59_875_839, 6687)
			// Standard Error: 141_696
			.saturating_add(Weight::from_parts(356_996, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `FileSystem::UserOperationPauseFlagsStorage` (r:1 w:0)
	/// Proof: `FileSystem::UserOperationPauseFlagsStorage` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:10 w:10)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:3 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `Providers::Buckets` (r:1 w:1)
	/// Proof: `Providers::Buckets` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(667), added: 3142, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::FixedRatePaymentStreams` (r:1 w:0)
	/// Proof: `PaymentStreams::FixedRatePaymentStreams` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:0)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:0 w:10)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1916), added: 4391, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:10)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn delete_files_bucket(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2416 + n * (1628 ±0)`
		//  Estimated: `8523 + n * (5009 ±0)`
		// Minimum execution time: 213_000_000 picoseconds.
		Weight::from_parts(100_224_043, 8523)
			// Standard Error: 7_236_247
			.saturating_add(Weight::from_parts(126_103_825, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(5_u64))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5009).saturating_mul(n.into()))
	}
	/// Storage: `FileSystem::UserOperationPauseFlagsStorage` (r:1 w:0)
	/// Proof: `FileSystem::UserOperationPauseFlagsStorage` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `Providers::Buckets` (r:1 w:0)
	/// Proof: `Providers::Buckets` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:10 w:10)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:6 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:0)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(667), added: 3142, mode: `MaxEncodedLen`)
	/// Storage: `Providers::UsedBspsCapacity` (r:1 w:1)
	/// Proof: `Providers::UsedBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::DynamicRatePaymentStreams` (r:1 w:1)
	/// Proof: `PaymentStreams::DynamicRatePaymentStreams` (`max_values`: None, `max_size`: Some(141), added: 2616, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::FixedRatePaymentStreams` (r:1 w:0)
	/// Proof: `PaymentStreams::FixedRatePaymentStreams` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::PrivilegedProviders` (r:1 w:0)
	/// Proof: `PaymentStreams::PrivilegedProviders` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::LastChargeableInfo` (r:1 w:0)
	/// Proof: `PaymentStreams::LastChargeableInfo` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Providers::TotalBspsCapacity` (r:1 w:0)
	/// Proof: `Providers::TotalBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::RegisteredUsers` (r:1 w:1)
	/// Proof: `PaymentStreams::RegisteredUsers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:0 w:10)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1916), added: 4391, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:10)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn delete_files_bsp(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2447 + n * (1758 ±0)`
		//  Estimated: `16056 + n * (5009 ±0)`
		// Minimum execution time: 328_000_000 picoseconds.
		Weight::from_parts(239_502_732, 16056)
			// Standard Error: 3_970_550
			.saturating_add(Weight::from_parts(139_655_737, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(23_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(7_u64))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5009).saturating_mul(n.into()))
	}
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:10 w:10)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1916), added: 4391, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:3 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:10 w:0)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Providers::Buckets` (r:1 w:1)
	/// Proof: `Providers::Buckets` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(667), added: 3142, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::FixedRatePaymentStreams` (r:1 w:0)
	/// Proof: `PaymentStreams::FixedRatePaymentStreams` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:0)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn delete_files_for_incomplete_storage_request_bucket(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1931 + n * (174 ±0)`
		//  Estimated: `8523 + n * (5009 ±0)`
		// Minimum execution time: 102_000_000 picoseconds.
		Weight::from_parts(87_355_191, 8523)
			// Standard Error: 3_428_787
			.saturating_add(Weight::from_parts(28_745_901, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5009).saturating_mul(n.into()))
	}
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:10 w:10)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1916), added: 4391, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:6 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Providers::Buckets` (r:1 w:0)
	/// Proof: `Providers::Buckets` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:10 w:0)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:0)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(667), added: 3142, mode: `MaxEncodedLen`)
	/// Storage: `Providers::UsedBspsCapacity` (r:1 w:1)
	/// Proof: `Providers::UsedBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::DynamicRatePaymentStreams` (r:1 w:1)
	/// Proof: `PaymentStreams::DynamicRatePaymentStreams` (`max_values`: None, `max_size`: Some(141), added: 2616, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::FixedRatePaymentStreams` (r:1 w:0)
	/// Proof: `PaymentStreams::FixedRatePaymentStreams` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::PrivilegedProviders` (r:1 w:0)
	/// Proof: `PaymentStreams::PrivilegedProviders` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::LastChargeableInfo` (r:1 w:0)
	/// Proof: `PaymentStreams::LastChargeableInfo` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Providers::TotalBspsCapacity` (r:1 w:0)
	/// Proof: `Providers::TotalBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::RegisteredUsers` (r:1 w:1)
	/// Proof: `PaymentStreams::RegisteredUsers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn delete_files_for_incomplete_storage_request_bsp(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1625 + n * (206 ±0)`
		//  Estimated: `16056 + n * (5009 ±0)`
		// Minimum execution time: 231_000_000 picoseconds.
		Weight::from_parts(191_158_469, 16056)
			// Standard Error: 3_509_861
			.saturating_add(Weight::from_parts(57_366_120, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(21_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5009).saturating_mul(n.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1916), added: 4391, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 39]`.
	fn revoke_storage_request(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1724 + n * (33 ±0)`
		//  Estimated: `6687`
		// Minimum execution time: 66_000_000 picoseconds.
		Weight::from_parts(67_707_602, 6687)
			// Standard Error: 61_164
			.saturating_add(Weight::from_parts(570_175, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(667), added: 3142, mode: `MaxEncodedLen`)
	/// Storage: `Providers::Buckets` (r:10 w:10)
	/// Proof: `Providers::Buckets` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Providers::InsolventProviders` (r:2 w:0)
	/// Proof: `Providers::InsolventProviders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AwaitingTopUpFromProviders` (r:2 w:0)
	/// Proof: `Providers::AwaitingTopUpFromProviders` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:200 w:200)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:3 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:0)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::FixedRatePaymentStreams` (r:1 w:0)
	/// Proof: `PaymentStreams::FixedRatePaymentStreams` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:0)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:200)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	/// The range of component `m` is `[1, 10]`.
	/// The range of component `l` is `[1, 10]`.
	fn msp_respond_storage_requests_multiple_buckets(n: u32, m: u32, l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + l * (7457 ±0) + m * (15308 ±0) + n * (22985 ±0)`
		//  Estimated: `101170 + l * (5992 ±7_525) + m * (5992 ±7_525) + n * (56082 ±0)`
		// Minimum execution time: 1_831_000_000 picoseconds.
		Weight::from_parts(1_831_000_000, 101170)
			// Standard Error: 138_080_117
			.saturating_add(Weight::from_parts(1_049_582_991, 0).saturating_mul(n.into()))
			// Standard Error: 138_080_117
			.saturating_add(Weight::from_parts(673_202_488, 0).saturating_mul(m.into()))
			.saturating_add(RocksDbWeight::get().reads(38_u64))
			.saturating_add(RocksDbWeight::get().reads((12_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(m.into())))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(l.into())))
			.saturating_add(RocksDbWeight::get().writes(45_u64))
			.saturating_add(RocksDbWeight::get().writes((23_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(m.into())))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(l.into())))
			.saturating_add(Weight::from_parts(0, 5992).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 5992).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 56082).saturating_mul(n.into()))
	}
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Providers::InsolventProviders` (r:2 w:0)
	/// Proof: `Providers::InsolventProviders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AwaitingTopUpFromProviders` (r:2 w:0)
	/// Proof: `Providers::AwaitingTopUpFromProviders` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:0)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:3 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ProofsDealer::ChallengesTicker` (r:1 w:0)
	/// Proof: `ProofsDealer::ChallengesTicker` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::GlobalBspsReputationWeight` (r:1 w:0)
	/// Proof: `Providers::GlobalBspsReputationWeight` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bsp_volunteer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2547`
		//  Estimated: `8523`
		// Minimum execution time: 99_000_000 picoseconds.
		Weight::from_parts(100_000_000, 8523)
			.saturating_add(RocksDbWeight::get().reads(16_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 39]`.
	fn process_expired_storage_request_msp_accepted_or_no_msp(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1724 + n * (33 ±0)`
		//  Estimated: `6687`
		// Minimum execution time: 49_000_000 picoseconds.
		Weight::from_parts(50_436_459, 6687)
			// Standard Error: 177_937
			.saturating_add(Weight::from_parts(419_953, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1916), added: 4391, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 39]`.
	fn process_expired_storage_request_msp_rejected(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1724 + n * (33 ±0)`
		//  Estimated: `6687`
		// Minimum execution time: 53_000_000 picoseconds.
		Weight::from_parts(59_875_839, 6687)
			// Standard Error: 141_696
			.saturating_add(Weight::from_parts(356_996, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `FileSystem::UserOperationPauseFlagsStorage` (r:1 w:0)
	/// Proof: `FileSystem::UserOperationPauseFlagsStorage` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:10 w:10)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:3 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `Providers::Buckets` (r:1 w:1)
	/// Proof: `Providers::Buckets` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(667), added: 3142, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::FixedRatePaymentStreams` (r:1 w:0)
	/// Proof: `PaymentStreams::FixedRatePaymentStreams` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:0)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:0 w:10)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1916), added: 4391, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:10)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn delete_files_bucket(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2416 + n * (1628 ±0)`
		//  Estimated: `8523 + n * (5009 ±0)`
		// Minimum execution time: 213_000_000 picoseconds.
		Weight::from_parts(100_224_043, 8523)
			// Standard Error: 7_236_247
			.saturating_add(Weight::from_parts(126_103_825, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(12_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5009).saturating_mul(n.into()))
	}
	/// Storage: `FileSystem::UserOperationPauseFlagsStorage` (r:1 w:0)
	/// Proof: `FileSystem::UserOperationPauseFlagsStorage` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `Providers::Buckets` (r:1 w:0)
	/// Proof: `Providers::Buckets` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:10 w:10)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:6 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:0)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(667), added: 3142, mode: `MaxEncodedLen`)
	/// Storage: `Providers::UsedBspsCapacity` (r:1 w:1)
	/// Proof: `Providers::UsedBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::DynamicRatePaymentStreams` (r:1 w:1)
	/// Proof: `PaymentStreams::DynamicRatePaymentStreams` (`max_values`: None, `max_size`: Some(141), added: 2616, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::FixedRatePaymentStreams` (r:1 w:0)
	/// Proof: `PaymentStreams::FixedRatePaymentStreams` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::PrivilegedProviders` (r:1 w:0)
	/// Proof: `PaymentStreams::PrivilegedProviders` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::LastChargeableInfo` (r:1 w:0)
	/// Proof: `PaymentStreams::LastChargeableInfo` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Providers::TotalBspsCapacity` (r:1 w:0)
	/// Proof: `Providers::TotalBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::RegisteredUsers` (r:1 w:1)
	/// Proof: `PaymentStreams::RegisteredUsers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:0 w:10)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1916), added: 4391, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:10)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn delete_files_bsp(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2447 + n * (1758 ±0)`
		//  Estimated: `16056 + n * (5009 ±0)`
		// Minimum execution time: 328_000_000 picoseconds.
		Weight::from_parts(239_502_732, 16056)
			// Standard Error: 3_970_550
			.saturating_add(Weight::from_parts(139_655_737, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(23_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5009).saturating_mul(n.into()))
	}
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:10 w:10)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1916), added: 4391, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:3 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:10 w:0)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Providers::Buckets` (r:1 w:1)
	/// Proof: `Providers::Buckets` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(667), added: 3142, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::FixedRatePaymentStreams` (r:1 w:0)
	/// Proof: `PaymentStreams::FixedRatePaymentStreams` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:0)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn delete_files_for_incomplete_storage_request_bucket(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1931 + n * (174 ±0)`
		//  Estimated: `8523 + n * (5009 ±0)`
		// Minimum execution time: 102_000_000 picoseconds.
		Weight::from_parts(87_355_191, 8523)
			// Standard Error: 3_428_787
			.saturating_add(Weight::from_parts(28_745_901, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5009).saturating_mul(n.into()))
	}
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:10 w:10)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1916), added: 4391, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:6 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Providers::Buckets` (r:1 w:0)
	/// Proof: `Providers::Buckets` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:1)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(683), added: 3158, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:10 w:0)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2534), added: 5009, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:0)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(667), added: 3142, mode: `MaxEncodedLen`)
	/// Storage: `Providers::UsedBspsCapacity` (r:1 w:1)
	/// Proof: `Providers::UsedBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::DynamicRatePaymentStreams` (r:1 w:1)
	/// Proof: `PaymentStreams::DynamicRatePaymentStreams` (`max_values`: None, `max_size`: Some(141), added: 2616, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::FixedRatePaymentStreams` (r:1 w:0)
	/// Proof: `PaymentStreams::FixedRatePaymentStreams` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::PrivilegedProviders` (r:1 w:0)
	/// Proof: `PaymentStreams::PrivilegedProviders` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::LastChargeableInfo` (r:1 w:0)
	/// Proof: `PaymentStreams::LastChargeableInfo` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Providers::TotalBspsCapacity` (r:1 w:0)
	/// Proof: `Providers::TotalBspsCapacity` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::RegisteredUsers` (r:1 w:1)
	/// Proof: `PaymentStreams::RegisteredUsers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn delete_files_for_incomplete_storage_request_bsp(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1625 + n * (206 ±0)`
		//  Estimated: `16056 + n * (5009 ±0)`
		// Minimum execution time: 231_000_000 picoseconds.
		Weight::from_parts(191_158_469, 16056)
			// Standard Error: 3_509_861
			.saturating_add(Weight::from_parts(57_366_120, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(21_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5009).saturating_mul(n.into()))
	}
}
