// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_file_system`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 52.0.0
//! DATE: 2026-02-11, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Mac`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/sh-solochain-evm-runtime/sh_solochain_evm_runtime.compact.compressed.wasm
// --pallet
// pallet_file_system
// --extrinsic
// revoke_storage_request,msp_respond_storage_requests_multiple_buckets,bsp_volunteer,bsp_confirm_storing,bsp_request_stop_storing,process_expired_storage_request_msp_accepted_or_no_msp,process_expired_storage_request_msp_rejected,delete_files_bucket,delete_files_bsp
// --exclude-extrinsics
// pallet_file_system::bsp_confirm_storing,pallet_file_system::bsp_request_stop_storing,pallet_file_system::delete_files_bucket,pallet_file_system::delete_files_bsp
// --steps
// 50
// --repeat
// 20
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/file-system/src/weights_new.rs
// --no-verify
// --allow-missing-host-functions
// --genesis-builder
// runtime

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_file_system`.
pub trait WeightInfo {
	fn revoke_storage_request(n: u32, ) -> Weight;
	fn msp_respond_storage_requests_multiple_buckets(n: u32, m: u32, l: u32, ) -> Weight;
	fn bsp_volunteer() -> Weight;
	fn process_expired_storage_request_msp_accepted_or_no_msp(n: u32, ) -> Weight;
	fn process_expired_storage_request_msp_rejected(n: u32, ) -> Weight;
}

/// Weights for `pallet_file_system` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2522), added: 4997, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1904), added: 4379, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 39]`.
	fn revoke_storage_request(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1653 + n * (33 ±0)`
		//  Estimated: `6687`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(60_933_486, 6687)
			// Standard Error: 2_967
			.saturating_add(Weight::from_parts(188_345, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(1143), added: 3618, mode: `MaxEncodedLen`)
	/// Storage: `Providers::Buckets` (r:10 w:10)
	/// Proof: `Providers::Buckets` (`max_values`: None, `max_size`: Some(179), added: 2654, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Providers::InsolventProviders` (r:2 w:0)
	/// Proof: `Providers::InsolventProviders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AwaitingTopUpFromProviders` (r:2 w:0)
	/// Proof: `Providers::AwaitingTopUpFromProviders` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:200 w:200)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2522), added: 4997, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:3 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:0)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(1159), added: 3634, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::FixedRatePaymentStreams` (r:1 w:0)
	/// Proof: `PaymentStreams::FixedRatePaymentStreams` (`max_values`: None, `max_size`: Some(125), added: 2600, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:0)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:200)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	/// The range of component `m` is `[1, 10]`.
	/// The range of component `l` is `[1, 10]`.
	fn msp_respond_storage_requests_multiple_buckets(n: u32, m: u32, l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + l * (7339 ±0) + m * (15188 ±0) + n * (22733 ±0)`
		//  Estimated: `100930 + l * (6516 ±757) + m * (6516 ±757) + n * (56486 ±0)`
		// Minimum execution time: 1_592_000_000 picoseconds.
		Weight::from_parts(1_725_000_000, 100930)
			// Standard Error: 12_593_730
			.saturating_add(Weight::from_parts(988_997_965, 0).saturating_mul(n.into()))
			// Standard Error: 12_593_730
			.saturating_add(Weight::from_parts(624_912_566, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(38_u64))
			.saturating_add(T::DbWeight::get().reads((12_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(l.into())))
			.saturating_add(T::DbWeight::get().writes(45_u64))
			.saturating_add(T::DbWeight::get().writes((24_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(l.into())))
			.saturating_add(Weight::from_parts(0, 6516).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 6516).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 56486).saturating_mul(n.into()))
	}
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Providers::InsolventProviders` (r:2 w:0)
	/// Proof: `Providers::InsolventProviders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AwaitingTopUpFromProviders` (r:2 w:0)
	/// Proof: `Providers::AwaitingTopUpFromProviders` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:0)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(1159), added: 3634, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2522), added: 4997, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:3 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `ProofsDealer::ChallengesTicker` (r:1 w:0)
	/// Proof: `ProofsDealer::ChallengesTicker` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::GlobalBspsReputationWeight` (r:1 w:0)
	/// Proof: `Providers::GlobalBspsReputationWeight` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	fn bsp_volunteer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2391`
		//  Estimated: `8523`
		// Minimum execution time: 88_000_000 picoseconds.
		Weight::from_parts(90_000_000, 8523)
			.saturating_add(T::DbWeight::get().reads(16_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2522), added: 4997, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 39]`.
	fn process_expired_storage_request_msp_accepted_or_no_msp(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1653 + n * (33 ±0)`
		//  Estimated: `6687`
		// Minimum execution time: 47_000_000 picoseconds.
		Weight::from_parts(48_766_016, 6687)
			// Standard Error: 2_449
			.saturating_add(Weight::from_parts(71_292, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2522), added: 4997, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1904), added: 4379, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 39]`.
	fn process_expired_storage_request_msp_rejected(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1653 + n * (33 ±0)`
		//  Estimated: `6687`
		// Minimum execution time: 48_000_000 picoseconds.
		Weight::from_parts(56_294_816, 6687)
			// Standard Error: 7_114
			.saturating_add(Weight::from_parts(90_913, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2522), added: 4997, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1904), added: 4379, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 39]`.
	fn revoke_storage_request(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1653 + n * (33 ±0)`
		//  Estimated: `6687`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(60_933_486, 6687)
			// Standard Error: 2_967
			.saturating_add(Weight::from_parts(188_345, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AccountIdToMainStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToMainStorageProviderId` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviders` (r:1 w:1)
	/// Proof: `Providers::MainStorageProviders` (`max_values`: None, `max_size`: Some(1143), added: 3618, mode: `MaxEncodedLen`)
	/// Storage: `Providers::Buckets` (r:10 w:10)
	/// Proof: `Providers::Buckets` (`max_values`: None, `max_size`: Some(179), added: 2654, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Providers::InsolventProviders` (r:2 w:0)
	/// Proof: `Providers::InsolventProviders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AwaitingTopUpFromProviders` (r:2 w:0)
	/// Proof: `Providers::AwaitingTopUpFromProviders` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:200 w:200)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2522), added: 4997, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:3 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:0)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(1159), added: 3634, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::FixedRatePaymentStreams` (r:1 w:0)
	/// Proof: `PaymentStreams::FixedRatePaymentStreams` (`max_values`: None, `max_size`: Some(125), added: 2600, mode: `MaxEncodedLen`)
	/// Storage: `Providers::MainStorageProviderIdsToValuePropositions` (r:1 w:0)
	/// Proof: `Providers::MainStorageProviderIdsToValuePropositions` (`max_values`: None, `max_size`: Some(1123), added: 3598, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:200)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	/// The range of component `m` is `[1, 10]`.
	/// The range of component `l` is `[1, 10]`.
	fn msp_respond_storage_requests_multiple_buckets(n: u32, m: u32, l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + l * (7339 ±0) + m * (15188 ±0) + n * (22733 ±0)`
		//  Estimated: `100930 + l * (6516 ±757) + m * (6516 ±757) + n * (56486 ±0)`
		// Minimum execution time: 1_592_000_000 picoseconds.
		Weight::from_parts(1_725_000_000, 100930)
			// Standard Error: 12_593_730
			.saturating_add(Weight::from_parts(988_997_965, 0).saturating_mul(n.into()))
			// Standard Error: 12_593_730
			.saturating_add(Weight::from_parts(624_912_566, 0).saturating_mul(m.into()))
			.saturating_add(RocksDbWeight::get().reads(38_u64))
			.saturating_add(RocksDbWeight::get().reads((12_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(m.into())))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(l.into())))
			.saturating_add(RocksDbWeight::get().writes(45_u64))
			.saturating_add(RocksDbWeight::get().writes((24_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(m.into())))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(l.into())))
			.saturating_add(Weight::from_parts(0, 6516).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 6516).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 56486).saturating_mul(n.into()))
	}
	/// Storage: `Providers::AccountIdToBackupStorageProviderId` (r:1 w:0)
	/// Proof: `Providers::AccountIdToBackupStorageProviderId` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Providers::InsolventProviders` (r:2 w:0)
	/// Proof: `Providers::InsolventProviders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Providers::AwaitingTopUpFromProviders` (r:2 w:0)
	/// Proof: `Providers::AwaitingTopUpFromProviders` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `Providers::BackupStorageProviders` (r:1 w:0)
	/// Proof: `Providers::BackupStorageProviders` (`max_values`: None, `max_size`: Some(1159), added: 3634, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2522), added: 4997, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:3 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `PaymentStreams::UsersWithoutFunds` (r:1 w:0)
	/// Proof: `PaymentStreams::UsersWithoutFunds` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `ProofsDealer::ChallengesTicker` (r:1 w:0)
	/// Proof: `ProofsDealer::ChallengesTicker` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Providers::GlobalBspsReputationWeight` (r:1 w:0)
	/// Proof: `Providers::GlobalBspsReputationWeight` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	fn bsp_volunteer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2391`
		//  Estimated: `8523`
		// Minimum execution time: 88_000_000 picoseconds.
		Weight::from_parts(90_000_000, 8523)
			.saturating_add(RocksDbWeight::get().reads(16_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2522), added: 4997, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 39]`.
	fn process_expired_storage_request_msp_accepted_or_no_msp(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1653 + n * (33 ±0)`
		//  Estimated: `6687`
		// Minimum execution time: 47_000_000 picoseconds.
		Weight::from_parts(48_766_016, 6687)
			// Standard Error: 2_449
			.saturating_add(Weight::from_parts(71_292, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `FileSystem::StorageRequests` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequests` (`max_values`: None, `max_size`: Some(2522), added: 4997, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::StorageRequestExpirations` (r:1 w:1)
	/// Proof: `FileSystem::StorageRequestExpirations` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::IncompleteStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::IncompleteStorageRequests` (`max_values`: None, `max_size`: Some(1904), added: 4379, mode: `MaxEncodedLen`)
	/// Storage: `FileSystem::BucketsWithStorageRequests` (r:0 w:1)
	/// Proof: `FileSystem::BucketsWithStorageRequests` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 39]`.
	fn process_expired_storage_request_msp_rejected(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1653 + n * (33 ±0)`
		//  Estimated: `6687`
		// Minimum execution time: 48_000_000 picoseconds.
		Weight::from_parts(56_294_816, 6687)
			// Standard Error: 7_114
			.saturating_add(Weight::from_parts(90_913, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
}
