# Sample configuration for StorageHub backend with mocks enabled
# This configuration uses mock implementations for testing

host = "127.0.0.1"
port = 8080

[storage_hub]
rpc_url = "ws://localhost:9944"
# Enable mock mode for StorageHub RPC (requires 'mocks' feature)
mock_mode = true

[database]
url = "postgres://localhost:5432/storage_hub"
# Enable mock mode for PostgreSQL (requires 'mocks' feature)
mock_mode = true