[package]
name = "pallet-evm-precompile-file-system"
authors = { workspace = true }
description = "A Precompile to manage the file-system pallet through the EVM."
edition = "2021"
version = "0.1.0"

[dependencies]

# Substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
codec = { workspace = true, features = ["max-encoded-len"] }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Frontier
evm = { workspace = true, features = ["with-codec"] }
fp-evm = { workspace = true }
pallet-evm = { workspace = true, features = ["forbid-evm-reentrancy"] }
precompile-utils = { workspace = true }

# StorageHub
pallet-file-system = { workspace = true }
shp-traits = { workspace = true }
storage-hub-runtime = { workspace = true }

[dev-dependencies]
hex-literal = { workspace = true }

pallet-balances = { workspace = true, features = ["insecure_zero_ed", "std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
codec = { workspace = true, features = ["max-encoded-len", "std"] }
precompile-utils = { workspace = true, features = ["std", "testing"] }
scale-info = { workspace = true, features = ["derive", "std"] }
sp-runtime = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
    "fp-evm/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-evm/std",
    "codec/std",
    "precompile-utils/std",
    "sp-core/std",
    "sp-io/std",
    "sp-std/std",
]
