[package]
name = "pallet-evm-precompile-file-system"
authors = { workspace = true }
description = "A Precompile to manage the file-system pallet through the EVM."
edition = "2021"
version = "0.1.0"

[dependencies]

# Substrate
codec = { workspace = true, features = ["max-encoded-len"] }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Frontier
fp-account = { workspace = true }
fp-evm = { workspace = true }
pallet-evm = { workspace = true, features = ["forbid-evm-reentrancy"] }
precompile-utils = { workspace = true }

# StorageHub
pallet-file-system = { workspace = true }
shp-traits = { workspace = true }
storage-hub-runtime = { workspace = true }

[dev-dependencies]
codec = { workspace = true, features = ["max-encoded-len", "std"] }
hex-literal = { workspace = true }
num-bigint = { workspace = true }

# Substrate
frame-support = { workspace = true, features = ["std"] }
frame-system = { workspace = true, features = ["std"] }
pallet-balances = { workspace = true, features = ["insecure_zero_ed", "std"] }
pallet-bucket-nfts = { workspace = true, features = ["std"] }
pallet-nfts = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
precompile-utils = { workspace = true, features = ["std", "testing"] }
scale-info = { workspace = true, features = ["derive", "std"] }
sp-core = { workspace = true, features = ["std"] }
sp-io = { workspace = true, features = ["std"] }
sp-runtime = { workspace = true, features = ["std"] }
sp-trie = { workspace = true, features = ["std"] }
sp-weights = { workspace = true, features = ["std"] }

# StorageHub
pallet-cr-randomness = { workspace = true, features = ["std"] }
pallet-payment-streams = { workspace = true, features = ["std"] }
pallet-proofs-dealer = { workspace = true, features = ["std"] }
pallet-storage-providers = { workspace = true, features = ["std"] }
shp-constants = { workspace = true, features = ["std"] }
shp-data-price-updater = { workspace = true, features = ["std"] }
shp-file-metadata = { workspace = true, features = ["std"] }
shp-traits = { workspace = true, features = ["std"] }
shp-treasury-funding = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
	"codec/std",
	"fp-evm/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-evm/std",
	"pallet-file-system/std",
	"precompile-utils/std",
	"shp-traits/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"storage-hub-runtime/std",
]
