[package]
name = "storagehub-wasm"
version = "0.1.0"
edition = "2021"
description = "WASM support for the StorageHub SDK"
license = "Apache-2.0"
repository = "https://github.com/moonsong-labs/storage-hub"

[lib]
crate-type = ["cdylib"]

[dependencies]
hex = { workspace = true }
parity-scale-codec = "3.7.4"
shp-constants = { workspace = true, default-features = false }
shp-file-metadata = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-runtime-interface = { workspace = true, default-features = false, features = ["disable_target_static_assertions"] }
sp-trie = { workspace = true, default-features = false }
wasm-bindgen = "0.2"
