version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: shc-indexer-postgres
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: shc-indexer
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data on your local machine

volumes:
  postgres_data:
