[package]
name = "shp-types"
description = "Primitives for generally used types of StorageHub"
version = "0.1.0"
homepage = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Substrate
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-trie = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = ["sp-runtime/runtime-benchmarks"]
std = ["sp-core/std", "sp-runtime/std", "sp-trie/std"]
try-runtime = ["sp-runtime/try-runtime"]
