[package]
name = "shp-opaque"
description = "Primitives for opaque types of StorageHub"
version = "0.1.0"
homepage = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Substrate
sp-runtime = { workspace = true }
parachains-common = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = ["sp-runtime/runtime-benchmarks"]
std = ["sp-runtime/std", "parachains-common/std"]
try-runtime = ["sp-runtime/try-runtime"]
