name: Publish SDK (core + msp-client)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish for packages (e.g., 0.1.0)"
        required: true
        type: string
  release:
    types: [published, edited]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.determine_version.outputs.version }}
      is_published_event: ${{ steps.set_is_published.outputs.is_published_event }}
    steps:
      - name: Determine version
        id: determine_version
        run: |
          EVENT_NAME="${{ github.event_name }}"
          INPUT_VERSION="${{ github.event.inputs.version }}"
          if [ "$EVENT_NAME" = "release" ]; then
            TAG="${{ github.event.release.tag_name }}"
            VERSION="${TAG#sdk-v}"
          else
            VERSION="$INPUT_VERSION"
          fi
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-.*)?$ ]]; then
            echo "Invalid version: $VERSION"; exit 1
          fi
          echo "Using version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Set published event flag
        id: set_is_published
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "is_published_event=true" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.event.action }}" = "published" ]; then
            echo "is_published_event=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_published_event=false" >> "$GITHUB_OUTPUT"
          fi

  publish:
    needs: prepare
    if: needs.prepare.outputs.is_published_event == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdk
    env:
      VERSION: ${{ needs.prepare.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node & pnpm setup
      - name: Setup pnpm & cache
        uses: ./.github/workflow-templates/setup-pnpm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SH_SDK_PUBLISH_TOKEN }}

      # Rust toolchain with wasm target
      - name: Setup Rust toolchain (for wasm)
        uses: actions-rust-lang/setup-rust-toolchain@v1.8
        with:
          target: wasm32-unknown-unknown
          cache: false

      # Cache wasm-pack binary
      - name: Cache wasm-pack
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/wasm-pack
          key: wasm-pack-v0.12.1

      - name: Install wasm-pack
        run: curl -sSf https://rustwasm.github.io/wasm-pack/installer/init.sh | sh

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Build WASM
      - name: Build WASM
        run: pnpm build:wasm

      # Set both package versions from input (no commit)
      - name: Set versions (no commit)
        run: |
          jq --arg v "$VERSION" '.version=$v' core/package.json > core/package.json.tmp && mv core/package.json.tmp core/package.json
          jq --arg v "$VERSION" '.version=$v' msp-client/package.json > msp-client/package.json.tmp && mv msp-client/package.json.tmp msp-client/package.json

      # Build packages
      - name: Build
        run: pnpm build

      # Preflight publish (dry-run)
      - name: Preflight dry-run publish
        run: pnpm publish -r --filter ./core --filter ./msp-client --dry-run --no-git-checks

      # Publish packages
      - name: Publish packages
        run: pnpm publish -r --filter ./core --filter ./msp-client --access public --no-git-checks

